Popup Branch -- Pair-Programming
LuisSalas94/My-Portfolio pull request #8
Opened 2022-01-26 14:45 UTC by LuisSalas94

**Hello Microverse Team**
In this branch We:
- Added HTML markup
- Added mobile version styles
- Added desktop version styles
- Added JavaScript functionality
- Fixed linters issues

Cheers and Happy coding!👏👏👏

2022-01-26 15:18 UTC, moise10r requested changes
### Hi **@Team,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- The popup is responsive, it fits mobile and desktop sizes properly.✔️ 
- You have a professional README file
-  Your Design looks awesome, keep rocking :rocket: 
 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


- [OPTIONAL ]  Your README looks great but you can improve it by making it more professional. A professional README file should have a project title, description, and instructions to set the project up locally. please refer to this [template](https://github.com/microverseinc/readme-template)

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-26 15:18 UTC, moise10r commented on index.html
> +								<ul>
- [ ] Kindly remove all unused code this will make your code mush noise, It is always a good practice to keep your code clean from such comments.

2022-01-26 15:18 UTC, moise10r commented on style.css
> +}
- [ ] Great implementation of the popup window :clap:  However You must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using the [templates in Figma.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

Your Design: 

![bad](https://user-images.githubusercontent.com/57562869/151190022-b32a11d7-c05a-47b9-bb65-5e2a4261075b.png)

Figma Design:

![coll](https://user-images.githubusercontent.com/57562869/151190080-8b313bdb-f077-4508-a010-e4945d66cac8.png)

2022-01-26 15:18 UTC, moise10r commented on index.html
>  				<img src="img/desktop/desktop-img1.jpg" alt="desktop image" />
https://github.com/LuisSalas94/My-Portfolio/blob/10cae6c3d5990eb3cdc699ca21445e1005420880/index.html#L129-L171

- [ ] As required :point_down: 

![image](https://user-images.githubusercontent.com/57421823/151015393-2368bdbc-0f28-46f4-9357-b17c3811e52d.png)

As seen above, all the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for projects list should be removed and instead it should be added via JavaScript.

This means you can use the `projects` array and logic that you already have, to populate the projects section of the main page entirely with javascript!

If you are struggling or don't know how to do so, here is an [example](https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95)

 - All those cards information should be stored into an array of objects then create a function to render through the array and create dynamically your HTML with the information from the object array, the works section must stay empty

2022-01-27 03:03 UTC, Meltrust approved these changes
Hi @LuisSalas94, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 04:01 UTC, merged